### ISSUE TITLE
Duplicate Checklist Titles

### ISSUE THREAD

**Issue by bennettBuckley** [KalAbaddon/listd.k13.app#40]
There are There are two Pilot and RIO Engine Start checklists in the F-14 section. They should be either labeled Engine Start 1 & 2, or name the first Prestart for each duplicate.

**Comment by KalAbaddon** [comment]
will check in to this and fix it.  sorry.

**Comment by KalAbaddon** [comment]
took a sec to find,  I accidently mislabeled a pre start as just start for both of them i think,  I will double check the manual and rename the correct one.

**Comment by KalAbaddon** [comment]
Should be all fixed.  Let me know if you notice anything else!

**Comment by KalAbaddon** [comment]
and again thanks for pointing it out!!
